# This file applies to ALL services unless they override it
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ewallet
    username: ewallet_admin
    password: 12345
  security:
    user:
      name: ${APP_SECURITY_USER_NAME:admin}
      password: ${APP_SECURITY_USER_PASSWORD:12345}
      roles: user




  

