# This file applies to ALL services unless they override it
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ewallet
    username: ewallet_admin
    password: 12345

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

spring:
  security:
    user:
      name: ${APP_SECURITY_USER_NAME:defaultuser}
      password: ${APP_SECURITY_USER_PASSWORD:defaultpass}
      roles: user

